name: Build + Test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Module
        shell: pwsh
        run: | 
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer, Pester, InvokeBuild -Scope CurrentUser
      - name: Invoke-Build
        shell: pwsh
        run: Invoke-Build .